/**
 * What a PUBLISHED package can do — and what it NEEDS — decided once at publication and carried to
 * the player.
 *
 * WHY THIS EXISTS (audit P0.5 — the first-activation identity hole)
 * The viewer's apply gate holds a section switch until the bridge acknowledges it with
 * SCRIPT_APPLIED. Until now the only way it could know a bridge acknowledges AT ALL was to watch
 * one arrive — `ackCapable` was learned IN-SESSION, from the first ack of the session. That makes
 * the FIRST activation of every package a guess, and the guess was "reveal": a pooled document
 * that has already painted its boot scene, its default sub-simulation, or the section a previous
 * warm pass ran was presented immediately, before any evidence that the REQUESTED section's body
 * had been applied. The viewer could show the wrong sub-simulation, once per package per session.
 *
 * The bridge itself has always known the answer — the generator either emits the SCRIPT_APPLIED
 * post or it does not — and that answer is a property of the published BYTES, so it is stable for
 * the life of a revision. Recording it at publication turns the first activation from a guess into
 * a lookup.
 *
 * WHAT ELSE LIVES HERE (audit P0.8 — the browser capability floor)
 * The same argument, asked of the ENTRY document instead of the bridge. The flagship packages
 * resolve `three` through `<script type="importmap">`; WebKit shipped import maps in Safari/iOS
 * 16.4, so on 16.3 and older those packages never paint at all. Whether a package needs one is a
 * property of its published bytes in exactly the way the ack is, so it is answered in the same
 * place, stored under the same key, projected in the same statement and delivered on the same
 * section field. The viewer turns it into a covered poster instead of a permanently blank frame.
 *
 * THREE STATES, NOT TWO
 * For every field: `true` proven, `false` proven-not, `null` UNKNOWN. Null is the honest answer for
 * every package published before that field existed, and each consumer treats it as its own case —
 * the apply gate neither reveals unverified pixels nor waits forever on a bridge that may be unable
 * to answer, and the capability floor never downgrades a package whose needs it does not know.
 * Collapsing null into either boolean is exactly the mistake this module exists to prevent.
 */

/**
 * The publication-time capability record.
 *
 * ONE RECORD, NOT ONE PER FACT (audit P0.8). `requiresImportMaps` is read off the ENTRY HTML, not
 * off the bridge, so it could have had a metadata key, a projection statement and a player field of
 * its own. It does not, deliberately: every fact here has the same lifetime (the bytes of one
 * revision), the same writer (a publication path), the same projection moment (the pointer flip)
 * and the same reader (the player, before the first activation). A second channel would be a second
 * thing to keep in step across activate, rollback and legacy migration — and the failure of that
 * would be silent, because a missing record is indistinguishable from an honest UNKNOWN.
 *
 * Every field is INDEPENDENTLY optional in practice: a publication path that can answer one
 * question and not the other records only what it knows (see `RevisionMigration`, which can read a
 * package's entry HTML while it has no bridge at all).
 */
export interface BridgeCapabilities {
  /** The bridge posts SCRIPT_APPLIED when a section body has been applied. */
  scriptApplied: boolean;
  /**
   * The entry HTML resolves bare module specifiers through `<script type="importmap">`.
   *
   * A REQUIREMENT, not an ability: WebKit shipped import maps in Safari/iOS 16.4, so on 16.3 and
   * older such a package does not run slowly — the bare specifier never resolves, no module
   * evaluates, and nothing ever paints. Recorded here so the viewer can cover exactly the packages
   * that cannot run on a given browser and nothing else.
   */
  requiresImportMaps?: boolean;
}

/** The half of the record that is read off the entry document rather than off the bridge. */
export interface EntryCapabilities {
  requiresImportMaps: boolean;
}

/** The key `BridgeCapabilities` is stored under inside `sim_revisions.metadata`. */
export const BRIDGE_CAPABILITIES_KEY = 'bridgeCapabilities';

/**
 * Does this assembled bridge acknowledge applied sections?
 *
 * Deliberately a SUBSTRING test on the assembled output rather than a parse. It is the same
 * technique `validateGeneratedBridge` already uses to assert the system-owned wrapper is intact
 * (SIM_READY / startScript / stopScript / the uiPolicy + autoPolicy handlers), applied to the same
 * text, at the same moment, for the same reason: the wrapper is generated by this codebase, so the
 * marker is not a heuristic about foreign code — it is a check that our own template landed.
 *
 * The two markers are required TOGETHER. `'SCRIPT_APPLIED'` alone appears in a comment or a string
 * table without any code posting it; requiring the `_post(` call site as well means the capability
 * describes behaviour rather than vocabulary.
 */
export function detectBridgeCapabilities(assembledBridgeJs: string): BridgeCapabilities {
  const posts = /_post\s*\(\s*\{[^}]*type\s*:\s*['"]SCRIPT_APPLIED['"]/.test(assembledBridgeJs);
  return { scriptApplied: posts };
}

/**
 * One `<script type="importmap">` START TAG, matched the way the HTML parser sees the attribute.
 *
 *   • attribute ORDER is free — `[^>]*` before `type` allows `<script async type=importmap>`;
 *   • QUOTING is free — double, single, or unquoted (all three are valid HTML);
 *   • WHITESPACE around `=` and inside the quotes is allowed, because the parser strips leading and
 *     trailing ASCII whitespace from the type attribute before comparing it;
 *   • CASE is free in both the tag and the value (`<SCRIPT TYPE="ImportMap">` is an import map).
 *
 * The value must be EXACTLY `importmap`: the quoted alternatives are anchored by their own closing
 * quote, and the unquoted one by the lookahead, so `type="importmap-shim"` (the polyfill's own
 * attribute, which no browser treats as an import map) does not match — and neither does the far
 * more common `type="module"`.
 */
const IMPORT_MAP_SCRIPT_RE =
  /<script\b[^>]*\btype\s*=\s*(?:"\s*importmap\s*"|'\s*importmap\s*'|importmap(?=[\s/>]))/i;

/**
 * The markup an import-map tag could REALLY be in: HTML comments and inline script BODIES removed.
 *
 * Both removals exist to stop a mention from being read as a use. A commented-out import map is not
 * an import map, and neither is the string `'<script type="importmap">'` sitting in a loader's
 * source — but a bare `.test()` over the raw document counts both, and each false positive posters
 * a package that would have run perfectly well.
 *
 * Removing script bodies is safe for the thing being looked for, because the opening tag is KEPT
 * (`$1`): an import map is found by its start tag, and its JSON body is never examined.
 */
function scannableMarkup(html: string): string {
  return html
    .replace(/<!--[\s\S]*?-->/g, ' ')
    .replace(/(<script\b[^>]*>)[\s\S]*?<\/script\s*>/gi, '$1');
}

/**
 * Does this entry document need import maps to run? (audit P0.8)
 *
 * A REGEX OVER MARKUP, AND ITS LIMITS ARE PART OF THE CONTRACT. This runs inside publication, on
 * customer-uploaded bytes, where a full parse would mean a parser dependency in the hot path of
 * every generation. What it therefore CANNOT see is stated so the answer is never over-read:
 *
 *   • an import map INJECTED AT RUNTIME (document.write, createElement) reads as `false`. Those
 *     packages are equally broken on an old WebKit, so this is an under-report, not a wrong one;
 *   • an import map inside a `<template>` — inert to the browser — reads as `true`;
 *   • an attribute value containing a literal `>` before `type` (`<script data-x="a>b"
 *     type=importmap>`) truncates the scan and reads as `false`;
 *   • it says nothing about WHICH specifiers are bare or whether they would have resolved anyway.
 *
 * The direction of every limit was chosen once: a false negative costs a blank frame on a browser
 * that was going to show one regardless, while a false positive replaces a working simulation with
 * a still image. So the detector only ever claims what it can actually see in the published bytes.
 */
export function detectEntryCapabilities(entryHtml: string): EntryCapabilities {
  return { requiresImportMaps: IMPORT_MAP_SCRIPT_RE.test(scannableMarkup(entryHtml)) };
}

/**
 * Read one boolean out of a revision's capability record, as the three-state answer.
 *
 * Total over garbage on purpose: `metadata` is a JSONB column written by several publication paths
 * across several releases, and a malformed or absent record must read as UNKNOWN — never as a
 * confident `false`, which would tell a consumer something it has no evidence for.
 */
function capabilityFromMetadata(metadata: unknown, field: keyof BridgeCapabilities): boolean | null {
  if (!metadata || typeof metadata !== 'object') return null;
  const caps = (metadata as Record<string, unknown>)[BRIDGE_CAPABILITIES_KEY];
  if (!caps || typeof caps !== 'object') return null;
  const value = (caps as Record<string, unknown>)[field];
  return typeof value === 'boolean' ? value : null;
}

/**
 * Does the published bridge acknowledge applied sections? `null` is UNKNOWN — never a confident
 * `false`, which would tell the gate to reveal a package it knows nothing about.
 */
export function bridgeAckCapableFromMetadata(metadata: unknown): boolean | null {
  return capabilityFromMetadata(metadata, 'scriptApplied');
}

/**
 * Does the published entry document need import maps? `null` is UNKNOWN — the honest answer for
 * every package published before the detector existed, and one the floor must never treat as
 * "requires": guessing would poster-only every legacy package on an older browser for a need it may
 * not have (`client-web/lib/sim/browserFloor.ts`).
 */
export function requiresImportMapsFromMetadata(metadata: unknown): boolean | null {
  return capabilityFromMetadata(metadata, 'requiresImportMaps');
}
