ALTER TABLE timeline_sections
  ADD COLUMN IF NOT EXISTS sim_prompt  TEXT,
  ADD COLUMN IF NOT EXISTS simple_ui   BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS auto_script BOOLEAN NOT NULL DEFAULT TRUE;
