/**
 * REAL-BROWSER simulation transition tests — frame-by-frame, no mocks of the child side.
 *
 * WHY THIS EXISTS: the bugs this branch fixes are visual and timing-dependent (a Full-UI flash
 * during a 200ms fade, the previous section visible for a frame, a blind timeout reveal). Message
 * and state assertions cannot prove that not a single wrong frame was presented, so this drives a
 * REAL iframe running the REAL generated artifacts — the actual head rAF gate, the actual
 * serve-time boot snippet and the actual combined bridge (generated by
 * backend-api/src/scripts/gen-sim-fixture.ts from the production code paths) — and records what is
 * ON SCREEN every animation frame.
 *
 * WHAT IS SAMPLED per frame (real values, mid-transition):
 *   overlayOpacity  getComputedStyle(overlay).opacity — the LIVE animated value during the fade
 *   controlsShown   the sim's own .controls display, read from the iframe document (same origin)
 *   section         the marker element's data-section — which sub-simulation is applied
 * The invariant asserted over the whole recorded sequence is the one the audit brief specifies:
 *   if overlayOpacity > 0 → the target section is applied AND no forbidden Full-UI control shows
 *                           AND no previous-section marker shows.
 *
 * SCOPE — read honestly: this validates the CHILD-side protocol and the transition ORDERING
 * (including the exact timings the player uses) in a real browser. The harness below replays the
 * player's message sequences from its OWN fixtures, so on its own it cannot prove the player
 * still emits them — a player-side regression would leave every test here green. The emitting
 * side is pinned separately, by source invariants in __tests__/transitionOrder.test.ts (atomic
 * exit, deferred-stop registration, gate ordering, mute/paint latches). Neither is a full
 * end-to-end run of the React viewer; that gap is still open.
 */
import { test, expect, type Page } from '@playwright/test';
import { createServer, type Server } from 'node:http';
import { readFileSync, existsSync, mkdirSync, statSync } from 'node:fs';
import { join, extname, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import type { AddressInfo } from 'node:net';

// ── Fixture package (generated from the REAL production generators) ──────────────────────

const FIXTURE_DIR = resolve(__dirname, '../../.sim-fixture');
const BACKEND = resolve(__dirname, '../../backend-api');

const SECTIONS = {
  A: 'aaaaaaaa-1111-4111-8111-aaaaaaaaaaaa',
  B: 'bbbbbbbb-2222-4222-8222-bbbbbbbbbbbb',
  SLOW: 'cccccccc-3333-4333-8333-cccccccccccc',
  THROWS: 'dddddddd-4444-4444-8444-dddddddddddd',
  AUTO: 'eeeeeeee-5555-4555-8555-eeeeeeeeeeee',
  MISSING: 'ffffffff-9999-4999-8999-ffffffffffff',
} as const;

// Must mirror the player's constants (useProjectPlayer.ts) — the harness replays its ordering.
const CSS_FADE_MS = 200;          // viewer.css .sim-overlay transition
const EXIT_STOP_MS = 280;         // SIM_EXIT_STOP_MS — deferred stopScript, > fade
const APPLY_ACK_MS = 200;         // SIM_APPLY_ACK_MS — legacy compatibility ceiling

function ensureFixture(): void {
  // The fixture is BUILT BY the production transforms (bridge template + rAF gate). A cached copy
  // from before a template change would quietly test the old bridge and pass — the suite would
  // certify code that no longer exists. Regenerate whenever the generator or the service that
  // feeds it is newer than the fixture. SIM_FIXTURE_FORCE=1 forces it.
  const stamp = join(FIXTURE_DIR, 'modern', 'index.html');
  if (existsSync(stamp) && !process.env.SIM_FIXTURE_FORCE) {
    const built = statSync(stamp).mtimeMs;
    const sources = [
      join(BACKEND, 'src', 'scripts', 'gen-sim-fixture.ts'),
      join(BACKEND, 'src', 'services', 'simulation', 'SimulationService.ts'),
    ];
    const stale = sources.some((s) => existsSync(s) && statSync(s).mtimeMs > built);
    if (!stale) return;
  }
  mkdirSync(FIXTURE_DIR, { recursive: true });
  const r = spawnSync('npx', ['tsx', 'src/scripts/gen-sim-fixture.ts', FIXTURE_DIR], { cwd: BACKEND, encoding: 'utf8' });
  if (r.status !== 0) throw new Error(`fixture generation failed: ${r.stderr || r.stdout}`);
}

const HARNESS_HTML = `<!doctype html>
<html><head><meta charset="utf-8"><style>
  html,body{margin:0;height:100%;background:#101010}
  /* Mirrors viewer.css .sim-overlay — the same 200ms opacity transition being audited. */
  #overlay{position:absolute;inset:0;opacity:0;pointer-events:none;transition:opacity .2s ease;z-index:20}
  #overlay.visible{opacity:1;pointer-events:auto}
  iframe{position:absolute;inset:0;width:100%;height:100%;border:0}
  /* Stand-in for the underlying video the player HOLDS during a non-painted entry. */
  #under{position:absolute;inset:0;background:#202080;z-index:1}
</style></head><body>
<div id="under"></div>
<div id="overlay"><iframe id="f" title="sim"></iframe></div>
<script>
(function(){
  var overlay = document.getElementById('overlay');
  var frame = document.getElementById('f');
  var H = window.__H = { samples: [], events: [], sampling:false, timers:[] };

  window.addEventListener('message', function(e){
    var d = e.data || {};
    if (d && d.type) H.events.push({ t: Math.round(performance.now()), type: d.type, script: d.script || null });
  });

  H.mount = function(pkg, section, bootHide){
    var url = '/' + pkg + '/index.html?section=' + section + '&v=1&dpr=1';
    if (bootHide && bootHide.length) url += '#simboot=' + encodeURIComponent(JSON.stringify({ hide: bootHide }));
    return new Promise(function(res){
      frame.addEventListener('load', function onl(){ frame.removeEventListener('load', onl); res(); });
      frame.src = url;
    });
  };
  H.send = function(msg){ frame.contentWindow.postMessage(msg, '*'); };
  H.waitFor = function(type, ms){
    var t0 = performance.now();
    return new Promise(function(res){
      (function poll(){
        for (var i=0;i<H.events.length;i++) if (H.events[i].type===type) return res(true);
        if (performance.now()-t0 > (ms||1000)) return res(false);
        requestAnimationFrame(poll);
      })();
    });
  };

  // ── the PLAYER's orderings, replayed verbatim ────────────────────────────────
  H.activate = function(script, params){                       // painted-path activation
    H.send({ type:'simResume' });
    H.send({ type:'startScript', script: script, params: params||{} });
    H.send({ type:'clearBootHide' });
    H.send({ type:'simRelayout' });
    H.send({ type:'simUnmute' });
  };
  H.reveal = function(){ overlay.classList.add('visible'); };
  H.hide   = function(){ overlay.classList.remove('visible'); };

  // NEW exit (this branch): freeze+mute FIRST, fade, stopScript DEFERRED past the fade.
  H.exitNew = function(){
    H.send({ type:'simPause' });
    H.send({ type:'simMute' });
    H.send({ type:'guidanceGate', active:false });
    H.hide();
    H.timers.push(setTimeout(function(){ H.send({ type:'stopScript' }); }, ${EXIT_STOP_MS}));
  };
  // OLD exit (pre-branch): stopScript at the boundary, THEN fade — the audited flash.
  H.exitOld = function(){
    H.send({ type:'stopScript' });
    H.hide();
    H.send({ type:'simPause' });
  };

  H.startSampling = function(){
    H.samples = []; H.sampling = true;
    (function loop(){
      if (!H.sampling) return;
      var s = { t: Math.round(performance.now()), op: parseFloat(getComputedStyle(overlay).opacity) || 0,
                controls: null, section: null };
      try {
        var doc = frame.contentDocument;
        if (doc) {
          var c = doc.querySelector('.controls');
          s.controls = c ? (getComputedStyle(c).display !== 'none') : null;
          var m = doc.getElementById('marker');
          s.section = m ? m.getAttribute('data-section') : null;
        }
      } catch (err) { s.err = String(err); }
      H.samples.push(s);
      requestAnimationFrame(loop);
    })();
  };
  H.stopSampling = function(){ H.sampling = false; return H.samples; };
  H.reset = function(){ H.events = []; H.samples = []; H.timers.forEach(clearTimeout); H.timers = []; };
})();
</script></body></html>`;

interface Sample { t: number; op: number; controls: boolean | null; section: string | null; err?: string }

let server: Server;
let base: string;

test.beforeAll(async () => {
  ensureFixture();
  server = createServer((req, res) => {
    const url = (req.url ?? '/').split('?')[0].split('#')[0];
    if (url === '/harness.html') {
      res.writeHead(200, { 'content-type': 'text/html; charset=utf-8' });
      res.end(HARNESS_HTML);
      return;
    }
    const file = join(FIXTURE_DIR, url.replace(/^\/+/, ''));
    if (!file.startsWith(FIXTURE_DIR) || !existsSync(file)) { res.writeHead(404); res.end('nope'); return; }
    const types: Record<string, string> = { '.html': 'text/html; charset=utf-8', '.js': 'application/javascript; charset=utf-8' };
    res.writeHead(200, { 'content-type': types[extname(file)] ?? 'text/plain', 'cache-control': 'no-cache' });
    res.end(readFileSync(file));
  });
  await new Promise<void>((r) => server.listen(0, '127.0.0.1', r));
  base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
});

test.afterAll(async () => { await new Promise<void>((r) => server.close(() => r())); });

// ── helpers ─────────────────────────────────────────────────────────────────────────────

async function openHarness(page: Page, pkg: 'modern' | 'legacy' | 'noraf', section: string, bootHide?: string[]) {
  await page.goto(`${base}/harness.html`);
  await page.evaluate(async ([p, s, bh]) => {
    await (window as any).__H.mount(p, s, bh);
  }, [pkg, section, bootHide ?? null] as const);
  // Wait for the bridge handshake so the document is genuinely ready to receive commands.
  await page.evaluate(() => (window as any).__H.waitFor('SIM_READY', 3000));
}

const samples = (page: Page) => page.evaluate(() => (window as any).__H.stopSampling() as Sample[]);
const startSampling = (page: Page) => page.evaluate(() => (window as any).__H.startSampling());
const events = (page: Page) => page.evaluate(() => (window as any).__H.events as { type: string; script: string | null }[]);

/** Every frame where anything of the sim was visible. */
const visible = (s: Sample[]) => s.filter((x) => x.op > 0);

// ── Tests ───────────────────────────────────────────────────────────────────────────────

test.describe('sim transitions — rendered frame sequence', () => {
  test('1. cold entry with Minimal UI never paints Full UI (boot cloak + gate + snippet)', async ({ page }) => {
    await openHarness(page, 'modern', SECTIONS.A, ['.controls']);
    await startSampling(page);
    await page.evaluate((s) => { (window as any).__H.activate(s, { simpleUi: true, autoScript: true, hideSelectors: ['.controls'] }); (window as any).__H.reveal(); }, SECTIONS.A);
    await page.waitForTimeout(600);
    const s = await samples(page);

    const shown = visible(s);
    expect(shown.length, 'the sim became visible').toBeGreaterThan(0);
    // NOT ONE visible frame may show the full-UI control panel.
    expect(shown.filter((x) => x.controls === true), 'Full-UI frames while Minimal UI expected').toHaveLength(0);
    expect(shown[shown.length - 1].section).toBe('A');
    await page.screenshot({ path: 'e2e-results/artifacts/sim-1-cold-minimal.png' });
  });

  test('2. A → B in the SAME package: no visible frame shows section A after the switch', async ({ page }) => {
    await openHarness(page, 'modern', SECTIONS.A);
    await page.evaluate((s) => { (window as any).__H.activate(s, {}); (window as any).__H.reveal(); }, SECTIONS.A);
    await page.waitForTimeout(300);

    await startSampling(page);
    await page.evaluate((s) => (window as any).__H.activate(s, {}), SECTIONS.B);
    await page.waitForTimeout(500);
    const s = await samples(page);

    // The switch is instantaneous in one document; from the first sample after it, B must be
    // applied. Assert no sample shows A once B has appeared (no flip-back / stale frame).
    const firstB = s.findIndex((x) => x.section === 'B');
    expect(firstB, 'section B applied').toBeGreaterThanOrEqual(0);
    expect(s.slice(firstB).filter((x) => x.section === 'A'), 'section A visible after B applied').toHaveLength(0);
    const ev = await events(page);
    expect(ev.some((e) => e.type === 'SCRIPT_APPLIED' && e.script === SECTIONS.B), 'B acked').toBe(true);
    await page.screenshot({ path: 'e2e-results/artifacts/sim-2-a-to-b.png' });
  });

  test('3. A → B → A repeatedly stays consistent and always ends on the requested section', async ({ page }) => {
    await openHarness(page, 'modern', SECTIONS.A);
    await page.evaluate((s) => { (window as any).__H.activate(s, {}); (window as any).__H.reveal(); }, SECTIONS.A);
    await page.waitForTimeout(200);
    for (let i = 0; i < 4; i++) {
      await page.evaluate((s) => (window as any).__H.activate(s, {}), SECTIONS.B);
      await page.waitForTimeout(80);
      await page.evaluate((s) => (window as any).__H.activate(s, {}), SECTIONS.A);
      await page.waitForTimeout(80);
    }
    const final = await page.evaluate(() => {
      const d = (document.getElementById('f') as HTMLIFrameElement).contentDocument!;
      return d.getElementById('marker')!.getAttribute('data-section');
    });
    expect(final).toBe('A');
  });

  test('4. Minimal-UI EXIT: the new deferred-stop ordering never restores Full UI while fading', async ({ page }) => {
    await openHarness(page, 'modern', SECTIONS.A, ['.controls']);
    await page.evaluate((s) => { (window as any).__H.activate(s, { simpleUi: true, hideSelectors: ['.controls'] }); (window as any).__H.reveal(); }, SECTIONS.A);
    await page.waitForTimeout(300);

    await startSampling(page);
    await page.evaluate(() => (window as any).__H.exitNew());
    await page.waitForTimeout(CSS_FADE_MS + EXIT_STOP_MS + 300);
    const s = await samples(page);

    // THE regression under test: with the OLD ordering the controls reappeared while opacity was
    // still ~1. Here: no frame with opacity > 0 may show the controls.
    const bad = visible(s).filter((x) => x.controls === true);
    expect(bad, `Full-UI frames during fade-out: ${JSON.stringify(bad.slice(0, 5))}`).toHaveLength(0);
    // …and the cleanup DID eventually run (the sim is genuinely released, not left configured).
    expect(s[s.length - 1].controls, 'controls restored after the fade completed').toBe(true);
    expect(s[s.length - 1].op).toBe(0);
    await page.screenshot({ path: 'e2e-results/artifacts/sim-4-exit-after.png' });
  });

  test('4b. CONTROL: the OLD ordering DOES flash Full UI mid-fade (proves the test discriminates)', async ({ page }) => {
    await openHarness(page, 'modern', SECTIONS.A, ['.controls']);
    await page.evaluate((s) => { (window as any).__H.activate(s, { simpleUi: true, hideSelectors: ['.controls'] }); (window as any).__H.reveal(); }, SECTIONS.A);
    await page.waitForTimeout(300);

    await startSampling(page);
    await page.evaluate(() => (window as any).__H.exitOld());
    await page.waitForTimeout(CSS_FADE_MS + 300);
    const s = await samples(page);

    // The bug, reproduced deterministically in a real browser.
    const flash = visible(s).filter((x) => x.controls === true);
    expect(flash.length, 'the old ordering must flash — otherwise test 4 proves nothing').toBeGreaterThan(0);
  });

  test('5. missing section id: runs NOTHING, reports SCRIPT_MISSING, never falls back to another body', async ({ page }) => {
    await openHarness(page, 'modern', SECTIONS.A);
    await page.evaluate((s) => (window as any).__H.activate(s, {}), SECTIONS.A);
    await page.waitForTimeout(150);
    await page.evaluate(() => (window as any).__H.reset());

    await page.evaluate((s) => (window as any).__H.activate(s, {}), SECTIONS.MISSING);
    await page.waitForTimeout(300);

    const ev = await events(page);
    expect(ev.some((e) => e.type === 'SCRIPT_MISSING'), 'SCRIPT_MISSING reported').toBe(true);
    expect(ev.some((e) => e.type === 'SCRIPT_APPLIED'), 'must NOT report applied').toBe(false);
    // The previous section's cleanup ran (stopScript) and NO other body was silently started.
    const applied = await page.evaluate(() =>
      JSON.stringify(((document.getElementById('f') as HTMLIFrameElement).contentWindow as unknown as { __APPLIED__?: string[] }).__APPLIED__ ?? []));
    expect(JSON.parse(applied).filter((x: string) => x === 'A')).toHaveLength(1);   // only the first activation
  });

  test('6. throwing cleanup is reported and does NOT wedge later section switches', async ({ page }) => {
    await openHarness(page, 'modern', SECTIONS.THROWS);
    await page.evaluate((s) => { (window as any).__H.activate(s, {}); (window as any).__H.reveal(); }, SECTIONS.THROWS);
    await page.waitForTimeout(150);
    await page.evaluate(() => (window as any).__H.reset());

    await page.evaluate((s) => (window as any).__H.activate(s, {}), SECTIONS.B);   // its cleanup throws here
    await page.waitForTimeout(300);

    const ev = await events(page);
    expect(ev.some((e) => e.type === 'SCRIPT_ERROR'), 'cleanup error surfaced').toBe(true);
    expect(ev.some((e) => e.type === 'SCRIPT_APPLIED' && e.script === SECTIONS.B), 'B still applied').toBe(true);
    // And the document keeps switching afterwards — the audited permanent wedge is gone.
    await page.evaluate((s) => (window as any).__H.activate(s, {}), SECTIONS.A);
    await page.waitForTimeout(200);
    const now = await page.evaluate(() => (document.getElementById('f') as HTMLIFrameElement).contentDocument!.getElementById('marker')!.getAttribute('data-section'));
    expect(now).toBe('A');
  });

  test("7. prototype name ('constructor') dispatches nothing and cannot brick the document", async ({ page }) => {
    await openHarness(page, 'modern', SECTIONS.A);
    await page.evaluate(() => (window as any).__H.activate('constructor', {}));
    await page.waitForTimeout(200);
    const ev = await events(page);
    expect(ev.some((e) => e.type === 'SCRIPT_MISSING')).toBe(true);
    await page.evaluate((s) => (window as any).__H.activate(s, {}), SECTIONS.B);
    await page.waitForTimeout(200);
    const now = await page.evaluate(() => (document.getElementById('f') as HTMLIFrameElement).contentDocument!.getElementById('marker')!.getAttribute('data-section'));
    expect(now).toBe('B');
  });

  test('8. LEGACY bridge never emits SCRIPT_APPLIED — and silently falls back on a missing section', async ({ page }) => {
    await openHarness(page, 'legacy', SECTIONS.A);
    await page.evaluate((s) => { (window as any).__H.activate(s, {}); (window as any).__H.reveal(); }, SECTIONS.A);
    await page.waitForTimeout(200);
    expect((await events(page)).some((e) => e.type === 'SCRIPT_APPLIED'), 'legacy cannot ack').toBe(false);

    // Documented legacy behaviour the player must defend against: an unknown section silently
    // runs the boot URL's default body instead of reporting.
    await page.evaluate((s) => (window as any).__H.activate(s, {}), SECTIONS.MISSING);
    await page.waitForTimeout(200);
    const now = await page.evaluate(() => (document.getElementById('f') as HTMLIFrameElement).contentDocument!.getElementById('marker')!.getAttribute('data-section'));
    expect(now, 'legacy silently ran the ?section= default').toBe('A');
  });

  test('10. user interaction during an auto-demo STOPS the automation but keeps the section intact', async ({ page }) => {
    await openHarness(page, 'modern', SECTIONS.AUTO, ['.controls']);
    await page.evaluate((s) => { (window as any).__H.activate(s, { simpleUi: true, autoScript: true, hideSelectors: ['.controls'] }); (window as any).__H.reveal(); }, SECTIONS.AUTO);
    await page.waitForTimeout(250);

    const readTicks = () => page.evaluate(() =>
      ((document.getElementById('f') as HTMLIFrameElement).contentWindow as unknown as { __TICKS__?: number }).__TICKS__ ?? -1);
    const running = await readTicks();
    expect(running, 'the auto-demo is ticking').toBeGreaterThan(2);

    // What the player sends on userInteraction — previously handled by NOBODY.
    await page.evaluate(() => (window as any).__H.send({ type: 'pauseScript' }));
    await page.waitForTimeout(60);
    const atPause = await readTicks();
    await page.waitForTimeout(300);
    const afterPause = await readTicks();

    expect(afterPause, 'automation must be genuinely stopped, not merely gated').toBe(atPause);
    expect((await events(page)).some((e) => e.type === 'AUTO_PAUSED')).toBe(true);

    // …while the simulation's OWN loop keeps running. The body-call timer capture cannot tell a
    // demo timer from an engine timer a synchronous SIM call scheduled (the generation prompt
    // specifies 30-150ms demo intervals — exactly engine-loop rates, so delay proves nothing),
    // and clearing the engine would FREEZE the scene: strictly worse than the automation it was
    // meant to stop. Only handles the body registered via simDemoTimer may be cleared (audited).
    const engineAtPause = await page.evaluate(() =>
      ((document.getElementById('f') as HTMLIFrameElement).contentWindow as unknown as { __ENGINE__?: number }).__ENGINE__ ?? -1);
    await page.waitForTimeout(200);
    const engineLater = await page.evaluate(() =>
      ((document.getElementById('f') as HTMLIFrameElement).contentWindow as unknown as { __ENGINE__?: number }).__ENGINE__ ?? -1);
    expect(engineLater, 'an UNREGISTERED (engine) timer must survive pauseScript').toBeGreaterThan(engineAtPause);

    // …and the section is STILL applied, still Minimal-UI, still visible: pausing is not a teardown.
    const state = await page.evaluate(() => {
      const d = (document.getElementById('f') as HTMLIFrameElement).contentDocument!;
      return {
        section: d.getElementById('marker')!.getAttribute('data-section'),
        controls: getComputedStyle(d.querySelector('.controls')!).display !== 'none',
        op: parseFloat(getComputedStyle(document.getElementById('overlay')!).opacity),
      };
    });
    expect(state.section).toBe('AUTO');
    expect(state.controls, 'Minimal-UI policy survives the pause').toBe(false);
    expect(state.op).toBe(1);
  });

  test('11. a sim that NEVER calls requestAnimationFrame still emits no false paint — and must stay displayable', async ({ page }) => {
    await openHarness(page, 'noraf', SECTIONS.A);
    // The honest-ack fix means no SIM_PAINTED is produced by bookkeeping callbacks…
    const painted = await page.evaluate(() => (window as any).__H.waitFor('SIM_PAINTED', 900));
    expect(painted, 'no false paint ack from the bridge/guidance bookkeeping').toBe(false);
    // …which is exactly why the player's hold MUST be terminal: this package would otherwise be
    // permanently undisplayable. The section still applies and the document is renderable.
    await page.evaluate((s) => (window as any).__H.activate(s, {}), SECTIONS.A);
    await page.evaluate(() => (window as any).__H.waitFor('SCRIPT_APPLIED', 2000));
    const applied = await page.evaluate(() =>
      (document.getElementById('f') as HTMLIFrameElement).contentDocument!.getElementById('marker')!.getAttribute('data-section'));
    expect(applied, 'the section applies normally — only the PAINT signal is absent').toBe('A');
  });

  test('9. a SLOW body (>200ms) still applies, and the ack arrives late — the ceiling case', async ({ page }) => {
    await openHarness(page, 'modern', SECTIONS.A);
    await page.evaluate((s) => { (window as any).__H.activate(s, {}); (window as any).__H.reveal(); }, SECTIONS.A);
    await page.waitForTimeout(200);
    await page.evaluate(() => (window as any).__H.reset());

    const t0 = Date.now();
    await page.evaluate((s) => (window as any).__H.activate(s, {}), SECTIONS.SLOW);
    await page.evaluate(() => (window as any).__H.waitFor('SCRIPT_APPLIED', 3000));
    const ackMs = Date.now() - t0;

    const ev = await events(page);
    expect(ev.some((e) => e.type === 'SCRIPT_APPLIED' && e.script === SECTIONS.SLOW)).toBe(true);
    // The fixture body blocks ~450ms — comfortably past the player's ${APPLY_ACK_MS}ms ceiling.
    expect(ackMs, 'slow body acks AFTER the compatibility ceiling').toBeGreaterThan(APPLY_ACK_MS);
  });
});
