/**
 * FULLY SYNTHETIC, LOOPBACK-ONLY fixture for the `sim-pool` browser gate.
 *
 * WHY THIS REPLACED THE OLD SEEDER
 * `seed-sim-pool-from-production.ts` (formerly seed-sim-pool-fixture.ts) copies rows out of a
 * hard-coded SOURCE_PROJECT and reuses that project's real `simulation_url`s and `hls_master_key`.
 * It therefore (a) cannot run at all against a fresh database, and (b) makes the browser fetch
 * simulation packages and HLS media from real storage. Neither is acceptable for a gate that must
 * prove nothing left loopback, so the DEFAULT e2e path is this file and that one is quarantined
 * behind an explicit opt-in flag.
 *
 * EVERYTHING HERE IS MANUFACTURED:
 *   • a synthetic org and owner (no existing rows consulted);
 *   • a synthetic project, two sequences, two videos, a choice point and an edge;
 *   • three simulation packages generated by `gen-sim-fixture.ts` — the REAL combined bridge, the
 *     REAL v4 rAF gate and the REAL v3 child runtime, only the section bodies are fixtures;
 *   • a tiny locally-encoded HLS ladder (ffmpeg, colour bars, no audio);
 *   • a locally rendered poster PNG per simulation;
 *   • revision + manifest rows and an active revision pointer, so the viewer exercises the real
 *     revision resolution path rather than the legacy one.
 *
 * All bytes are written through the storage adapter, which MUST be the local disk adapter — the
 * script refuses to run otherwise, so it can never write into a cloud bucket.
 *
 * Deterministic ids are printed as a JSON manifest on stdout (and written to --manifest <path>) so
 * the harness never hard-codes a hidden UUID.
 *
 *   Seed:   DATABASE_URL=... STORAGE_BACKEND=local tsx src/scripts/seed-sim-pool-synthetic.ts
 *   Delete: DATABASE_URL=... STORAGE_BACKEND=local tsx src/scripts/seed-sim-pool-synthetic.ts --delete
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, readdirSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash, randomUUID } from 'node:crypto';
import { eq } from 'drizzle-orm';

import { db } from '../db/index.js';
import {
  orgs, users, projects, video_files, timeline_sections, simulations,
  branch_sequences, branch_choice_points, branch_edges, sim_revisions,
} from '../db/schema.js';
import { getStorageAdapter } from '../services/storage/getStorageAdapter.js';
import { LocalStorageAdapter } from '../services/storage/LocalStorageAdapter.js';
import { getSimulationContentType } from '../services/simulation/SimulationService.js';

const HERE = dirname(fileURLToPath(import.meta.url));

/** Deterministic — the harness reads these back from the manifest rather than hard-coding them. */
const IDS = {
  org:     '0f1c7e00-0000-4000-a000-00000000000f',
  owner:   '0f1c7e00-0000-4000-a000-00000000000e',
  project: '00000000-0000-4000-a000-0000000f1c7e',
  simA:    '0f1c7e01-0000-4000-a000-000000000001',
  simB:    '0f1c7e01-0000-4000-a000-000000000002',
  simC:    '0f1c7e01-0000-4000-a000-000000000003',
} as const;

/** Section ids inside the generated packages (printed by gen-sim-fixture as its descriptor). */
const SECTION = {
  A: 'aaaaaaaa-1111-4111-8111-aaaaaaaaaaaa',
  B: 'bbbbbbbb-2222-4222-8222-bbbbbbbbbbbb',
  V3A: '33333333-a111-4a11-8a11-333333333333',
} as const;

const log = (...a: unknown[]) => console.error(...a);   // stdout stays pure JSON manifest

async function wipe(): Promise<void> {
  // Project delete cascades to videos/sections/branching (migration 035). Simulations, org and
  // owner are removed explicitly because they are not children of the project row.
  await db.delete(simulations).where(eq(simulations.project_id, IDS.project));
  await db.delete(projects).where(eq(projects.id, IDS.project));
  await db.delete(users).where(eq(users.id, IDS.owner));
  await db.delete(orgs).where(eq(orgs.id, IDS.org));
}

function generatePackages(): string {
  const out = mkdtempSync(join(tmpdir(), 'simpool-pkgs-'));
  execFileSync('npx', ['tsx', join(HERE, 'gen-sim-fixture.ts'), out], {
    cwd: join(HERE, '..', '..'), stdio: ['ignore', 'pipe', 'pipe'],
  });
  return out;
}

/** A tiny, deterministic, locally encoded HLS ladder. No network, no real media. */
function buildHls(seconds: number): { dir: string; files: string[] } {
  const dir = mkdtempSync(join(tmpdir(), 'simpool-hls-'));
  execFileSync('ffmpeg', [
    '-hide_banner', '-loglevel', 'error', '-y',
    '-f', 'lavfi', '-i', `testsrc=size=320x180:rate=15:duration=${seconds}`,
    '-c:v', 'libx264', '-preset', 'ultrafast', '-pix_fmt', 'yuv420p', '-g', '30',
    '-hls_time', '4', '-hls_playlist_type', 'vod',
    '-hls_segment_filename', join(dir, 'seg_%03d.ts'),
    join(dir, 'index.m3u8'),
  ], { stdio: ['ignore', 'pipe', 'pipe'] });
  // A master playlist pointing at the single rendition, which is what hls_master_key expects.
  writeFileSync(join(dir, 'master.m3u8'),
    '#EXTM3U\n#EXT-X-VERSION:3\n#EXT-X-STREAM-INF:BANDWIDTH=300000,RESOLUTION=320x180\nindex.m3u8\n');
  return { dir, files: readdirSync(dir) };
}

/** A 1x1 opaque PNG — enough for the cold-seek poster path without shipping real artwork. */
const POSTER_PNG = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
  'base64',
);

async function main(): Promise<void> {
  const argv = process.argv.slice(2);
  const storage = getStorageAdapter();
  if (!(storage instanceof LocalStorageAdapter)) {
    throw new Error('refusing to run: STORAGE_BACKEND must resolve to the LOCAL disk adapter — '
      + 'this fixture must never write into a cloud bucket');
  }
  if (argv.includes('--delete')) {
    await wipe();
    log('🗑  synthetic sim-pool fixture deleted (storage objects left in place — local disk only)');
    process.stdout.write(JSON.stringify({ deleted: true, ...IDS }, null, 1) + '\n');
    process.exit(0);
  }

  await wipe();

  // ── org + owner, entirely manufactured ────────────────────────────────────────────────────────
  await db.insert(orgs).values({ id: IDS.org, name: '[SYNTHETIC] sim-pool org' } as typeof orgs.$inferInsert);
  await db.insert(users).values({
    id: IDS.owner, firebase_uid: 'synthetic-simpool-owner', email: 'simpool@localhost.invalid',
  } as typeof users.$inferInsert);

  await db.insert(projects).values({
    id: IDS.project, org_id: IDS.org, created_by: IDS.owner,
    title: '[SYNTHETIC] Sim Pool — 3 local packages + branching',
    topic: 'Loopback-only sim-pool fixture: package A twice, package B once, legacy package C on a branch',
    visibility: 'public',
  } as typeof projects.$inferInsert);

  // ── packages: real bridge + real child runtime, generated locally ─────────────────────────────
  const pkgDir = generatePackages();
  const PACKAGES = [
    { id: IDS.simA, src: 'modern', name: 'synthetic-a' },
    { id: IDS.simB, src: 'v3allmanaged', name: 'synthetic-b' },
    // `nopaint` is the only generated package that advertises a BARE SIM_READY (dispatch: null),
    // which is what makes the viewer treat it as load-time-locked and take the per-URL NAVIGATION
    // fallback. The `legacy` package still advertises `dispatch: 'dynamic'`, so it gets pooled and
    // never exercises that path — the branch-only package has to be this one.
    { id: IDS.simC, src: 'nopaint', name: 'synthetic-c-nodispatch' },
  ];
  const simUrl: Record<string, string> = {};
  for (const p of PACKAGES) {
    const prefix = `simulations/${IDS.project}/${p.id}`;
    let bridgeHash = '';
    for (const f of readdirSync(join(pkgDir, p.src))) {
      const bytes = readFileSync(join(pkgDir, p.src, f));
      if (f === 'bridge.js') bridgeHash = createHash('sha256').update(bytes).digest('hex').slice(0, 12);
      await storage.uploadFile(`${prefix}/${f}`, bytes, getSimulationContentType(f));
    }
    await storage.uploadFile(`${prefix}/poster.png`, POSTER_PNG, 'image/png');
    const entryKey = `${prefix}/index.html`;
    await db.insert(simulations).values({
      id: p.id, project_id: IDS.project, name: p.name,
      storage_prefix: prefix, entry_file: entryKey, bridge_hash: bridgeHash,
    } as typeof simulations.$inferInsert);
    // A revision row + active pointer, so the viewer resolves through the REAL revision path.
    const revId = randomUUID();
    // `activated_at` is required by sim_revisions_activated_at_chk for any terminal status —
    // an 'active' revision that was never activated is exactly the inconsistency it forbids.
    await db.insert(sim_revisions).values({
      id: revId, simulation_id: p.id, revision_number: 1, status: 'active',
      activated_at: new Date('2026-01-01T00:00:00Z'),
      entry_path: 'package/index.html', manifest_hash: createHash('sha256').update(p.id).digest('hex'),
      created_by: 'seed-sim-pool-synthetic',
    } as typeof sim_revisions.$inferInsert);
    simUrl[p.id] = `${storage.getSimPublicUrl(entryKey)}?v=${bridgeHash}`;
  }
  rmSync(pkgDir, { recursive: true, force: true });

  // ── a tiny locally encoded video, one per sequence ────────────────────────────────────────────
  const hls = buildHls(95);
  const hlsPrefix = `hls/${IDS.project}`;
  for (const f of hls.files) {
    await storage.uploadFile(`${hlsPrefix}/${f}`, readFileSync(join(hls.dir, f)),
      f.endsWith('.m3u8') ? 'application/vnd.apple.mpegurl' : 'video/mp2t');
  }
  rmSync(hls.dir, { recursive: true, force: true });

  const [entrySeq] = await db.insert(branch_sequences).values({
    project_id: IDS.project, label: 'Main path', is_entry: true, sort_order: 0,
  }).returning();
  const [branchSeq] = await db.insert(branch_sequences).values({
    project_id: IDS.project, label: 'Deep dive', is_entry: false, sort_order: 1,
  }).returning();

  const mkVideo = async (seqId: string, order: number) => {
    const [v] = await db.insert(video_files).values({
      project_id: IDS.project, filename: 'synthetic.mp4', status: 'ready',
      duration_sec: 95, hls_status: 'ready',
      hls_master_key: `${hlsPrefix}/master.m3u8`, is_broll: false,
      sequence_id: seqId, sequence_order: order,
    } as typeof video_files.$inferInsert).returning();
    return v!;
  };
  const entryVid = await mkVideo(entrySeq!.id, 0);
  const branchVid = await mkVideo(branchSeq!.id, 0);

  const mkSim = (
    videoId: string, start: number, end: number, simId: string, section: string,
    simpleUi: boolean, label: string,
  ) => ({
    project_id: IDS.project, video_file_id: videoId, start_sec: start, end_sec: end,
    type: 'simulation', track: 'main',
    simulation_url: `${simUrl[simId]}&section=${section}`,
    simulation_id: simId, sim_script: 'main', simple_ui: simpleUi, auto_script: true, label,
    ...(simpleUi ? { sim_meta: { uiControls: { hide: ['button'] } } } : {}),
  } as typeof timeline_sections.$inferInsert);

  await db.insert(timeline_sections).values([
    // Package A appears TWICE with different section bodies and different UI config — the case the
    // pool exists for (one resident document serving two sections).
    mkSim(entryVid.id, 20, 35, IDS.simA, SECTION.A, true,  'A1 synthetic-a (minimal UI)'),
    mkSim(entryVid.id, 50, 62, IDS.simA, SECTION.B, false, 'A2 synthetic-a (full UI)'),
    // A second, distinct package.
    mkSim(entryVid.id, 72, 88, IDS.simB, SECTION.V3A, false, 'B synthetic-b'),
    // Branch-only legacy package — must NOT be pooled while on the main path.
    mkSim(branchVid.id, 15, 40, IDS.simC, SECTION.A, false, 'C synthetic-c (legacy bridge)'),
  ]);

  const [cp] = await db.insert(branch_choice_points).values({
    project_id: IDS.project, sequence_id: entrySeq!.id, lead_in_sec: 6, timeout_sec: 8,
    behavior: 'continue', prompt: 'Go deeper?', layout: 'cards',
  }).returning();
  await db.insert(branch_edges).values({
    project_id: IDS.project, choice_point_id: cp!.id, label: 'Deep dive',
    destination_type: 'sequence', dest_sequence_id: branchSeq!.id, sort_order: 0,
  });

  const manifest = {
    ...IDS,
    entrySequenceId: entrySeq!.id, branchSequenceId: branchSeq!.id,
    entryVideoId: entryVid.id, branchVideoId: branchVid.id,
    viewPath: `/projects/${IDS.project}/view`,
    sections: [
      { label: 'A1', simulationId: IDS.simA, start: 20, end: 35, minimalUi: true },
      { label: 'A2', simulationId: IDS.simA, start: 50, end: 62, minimalUi: false },
      { label: 'B', simulationId: IDS.simB, start: 72, end: 88, minimalUi: false },
      { label: 'C', simulationId: IDS.simC, start: 15, end: 40, branchOnly: true },
    ],
    storage: 'local-disk',
    cleanup: 'tsx src/scripts/seed-sim-pool-synthetic.ts --delete',
  };
  const mi = argv.indexOf('--manifest');
  if (mi >= 0 && argv[mi + 1]) writeFileSync(argv[mi + 1]!, JSON.stringify(manifest, null, 1));
  log('✅ synthetic sim-pool fixture seeded (loopback only)');
  process.stdout.write(JSON.stringify(manifest, null, 1) + '\n');
  process.exit(0);
}

main().catch((e) => { console.error(e); process.exit(1); });
