/**
 * simulation-004 — a served simulation document must only obey its OWN parent.
 *
 * Every system script the platform injects into a sim document installs a `message` listener, and
 * none of them looked at `event.source`. `frame-ancestors` stops an attacker page from FRAMING a
 * sim, but it does not stop one from holding a handle to it: `window.open('/sim-public/…')` returns
 * a live window reference, and any third-party frame nested inside the customer's own package can
 * post to `window.parent`. Either one could swap the running section, stop it, freeze the scene,
 * mute it, force the Minimal-UI hide set, or silence every guidance cue.
 *
 * These tests run the ACTUAL generated sources in a `vm` context with a hand-built window, so they
 * fail on behaviour rather than on the presence of a string.
 *
 * WHY SOURCE AND NOT ORIGIN. The audit's suggested fix also pinned `event.origin` to an allow-list
 * baked into the generated bytes. Two things make that wrong here:
 *   • bridge.js and the gate are STORED at publication time, so a baked origin list freezes the
 *     deploy topology into every published package forever — the exact failure the sim CSP's
 *     comment already calls out for `frame-ancestors` ("a newly-added app origin could never reach
 *     an already-cached document"), except permanent.
 *   • the export capture backend navigates DIRECTLY to the sim URL and drives it with
 *     `window.postMessage(m, '*')` from the page itself (playwrightScreenshotBackend.ts,
 *     beginFrameBackend.ts). Those messages carry the SIM's own origin, which is not an app origin,
 *     so an origin allow-list would break every linear video export.
 * `event.source !== window.parent` rejects both attacker shapes and admits both real drivers: the
 * player posts through `frame.contentWindow` (source === parent) and capture self-posts on a
 * top-level page (source === window === window.parent).
 */
import { describe, it, expect } from 'vitest';
import vm from 'node:vm';
import {
  injectRafGate,
  injectInlineBridge,
  wrapBridgeMainBody,
  wrapBridgeCombined,
  type BridgeFunction,
} from '../SimulationService.js';
import { wrapGuidanceCombined, type GuidanceEntryStored } from '../GuidanceService.js';
import { injectSimBootSnippet } from '../../../controllers/sim-public.controller.js';

type Msg = Record<string, unknown>;

interface Harness {
  /** Everything the document posted to its parent. */
  parentPosts: Msg[];
  /** Deliver a message event whose `source` is (or is not) the document's real parent. */
  fire(data: Msg, from: 'parent' | 'foreign'): void;
  /** Run every rAF callback queued so far, once, with `ts`. */
  flushRaf(ts: number): void;
  win: Record<string, unknown> & { [k: string]: any };  // eslint-disable-line @typescript-eslint/no-explicit-any
}

/** A window/document just real enough to run the injected system scripts. */
function runInSimDocument(source: string, setup?: (win: any) => void): Harness { // eslint-disable-line @typescript-eslint/no-explicit-any
  const parentPosts: Msg[] = [];
  const messageListeners: Array<(e: unknown) => void> = [];
  let rafQueue: Array<(ts: number) => void> = [];
  const byId = new Map<string, any>(); // eslint-disable-line @typescript-eslint/no-explicit-any

  const makeEl = (tag: string): any => { // eslint-disable-line @typescript-eslint/no-explicit-any
    const e: any = { // eslint-disable-line @typescript-eslint/no-explicit-any
      tagName: tag.toUpperCase(), id: '', textContent: '', value: '', checked: false,
      style: {}, children: [] as unknown[], parentElement: null, removed: false,
      appendChild(c: any) { // eslint-disable-line @typescript-eslint/no-explicit-any
        e.children.push(c); c.parentElement = e; if (c.id) byId.set(c.id, c); return c;
      },
      remove() { e.removed = true; if (e.id) byId.delete(e.id); },
      setAttribute() {}, getAttribute() { return null; },
      addEventListener() {}, removeEventListener() {},
      querySelectorAll: () => [] as unknown[],
      getBoundingClientRect: () => ({ width: 0, height: 0, top: 0, left: 0, right: 0, bottom: 0 }),
    };
    return e;
  };

  const documentEl = makeEl('html');
  const head = makeEl('head');
  const body = makeEl('body');

  const document: any = { // eslint-disable-line @typescript-eslint/no-explicit-any
    readyState: 'complete',
    head, body, documentElement: documentEl,
    addEventListener() {}, removeEventListener() {},
    getElementById: (id: string) => byId.get(id) ?? null,
    createElement: (tag: string) => makeEl(tag),
    querySelectorAll: () => [] as unknown[],
    querySelector: () => null,
    dispatchEvent: () => true,
  };

  const parent = { postMessage: (m: Msg) => { parentPosts.push(m); } };

  const win: any = { // eslint-disable-line @typescript-eslint/no-explicit-any
    document,
    parent,
    location: { hash: '', search: '', href: 'https://api.example.test/sim-public/s/index.html', origin: 'https://api.example.test' },
    addEventListener(type: string, fn: (e: unknown) => void) { if (type === 'message') messageListeners.push(fn); },
    removeEventListener() {},
    requestAnimationFrame(cb: (ts: number) => void) { rafQueue.push(cb); return rafQueue.length; },
    cancelAnimationFrame() {},
    getComputedStyle: () => ({ display: 'block', visibility: 'visible' }),
  };
  win.window = win;
  win.self = win;
  setup?.(win);

  const context = vm.createContext({
    window: win,
    document,
    // Bare `location` / `navigator` are referenced unqualified by some generated blocks.
    location: win.location,
    navigator: { userAgent: 'vitest', hardwareConcurrency: 4 },
    // Deliberately inert: the templates all arm a `setTimeout(fireReady, 3000)` fallback, and a
    // real timer would make the assertions depend on wall clock.
    setTimeout: (_fn: unknown, _ms?: number) => 0,
    clearTimeout: () => {},
    setInterval: () => 0,
    clearInterval: () => {},
    requestAnimationFrame: (cb: (ts: number) => void) => win.requestAnimationFrame(cb),
    cancelAnimationFrame: () => {},
    URLSearchParams,
    Event: class { constructor(public type: string) {} },
    console,
    Date,
  });
  vm.runInContext(source, context, { timeout: 5_000 });

  return {
    parentPosts,
    fire(data, from) {
      const event = from === 'parent'
        ? { data, source: parent, origin: 'https://app.example.test' }
        // A window that is NOT this document's parent: the opener of a window.open(), or a
        // third-party frame nested inside the customer's own package.
        : { data, source: { postMessage() {} }, origin: 'https://evil.example' };
      for (const fn of [...messageListeners]) fn(event);
    },
    flushRaf(ts) {
      const batch = rafQueue;
      rafQueue = [];
      for (const cb of batch) cb(ts);
    },
    win,
  };
}

/** Pull one injected `<script>` body out of an HTML document by a marker it contains. */
function scriptContaining(html: string, marker: string): string {
  const bodies = [...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map((m) => m[1]);
  const found = bodies.find((b) => b.includes(marker));
  if (!found) throw new Error(`no injected <script> containing ${JSON.stringify(marker)}`);
  return found;
}

const BARE_HTML = '<!doctype html><html><head></head><body></body></html>';

// ── 1. Serve-time boot snippet (sim-public.controller.ts) ─────────────────────

describe('boot snippet — clearBootHide', () => {
  const bootSource = () => scriptContaining(injectSimBootSnippet(BARE_HTML), '__simBootHide');
  const withBootCloak = (win: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
    win.location.hash = '#simboot=' + encodeURIComponent(JSON.stringify({ hide: ['#panel'] }));
  };

  it('ignores clearBootHide from a window that is not the parent', () => {
    const h = runInSimDocument(bootSource(), withBootCloak);
    expect(h.win.document.getElementById('__simBootHide'), 'setup: no boot cloak was installed').not.toBeNull();

    h.fire({ type: 'clearBootHide' }, 'foreign');

    expect(h.win.document.getElementById('__simBootHide'),
      'a foreign window stripped the minimal-UI boot cloak').not.toBeNull();
  });

  it('still honours clearBootHide from the real parent', () => {
    const h = runInSimDocument(bootSource(), withBootCloak);
    h.fire({ type: 'clearBootHide' }, 'parent');
    expect(h.win.document.getElementById('__simBootHide')).toBeNull();
  });
});

// ── 2. rAF gate (head-injected) ───────────────────────────────────────────────

describe('rAF gate — simPause/simResume', () => {
  const gateSource = () => scriptContaining(injectRafGate(BARE_HTML), '__SIM_RAF_GATE__');

  it('ignores simPause from a window that is not the parent', () => {
    const h = runInSimDocument(gateSource());
    expect(h.win.__SIM_RAF_GATE__.isPaused(), 'setup: the gate booted paused').toBe(false);

    h.fire({ type: 'simPause' }, 'foreign');

    expect(h.win.__SIM_RAF_GATE__.isPaused(), 'a foreign window froze the simulation').toBe(false);
  });

  it('still honours simPause/simResume from the real parent', () => {
    const h = runInSimDocument(gateSource());
    h.fire({ type: 'simPause' }, 'parent');
    expect(h.win.__SIM_RAF_GATE__.isPaused()).toBe(true);
    h.fire({ type: 'simResume' }, 'parent');
    expect(h.win.__SIM_RAF_GATE__.isPaused()).toBe(false);
  });
});

// ── 3. Inline v2 bridge (BRIDGE_TEMPLATE, injected at upload time) ────────────

describe('inline bridge — startScript', () => {
  const FNS: BridgeFunction[] = [{ name: 'demo', windowFn: 'runDemo', description: 'demo' }];
  const inlineSource = () => scriptContaining(injectInlineBridge(BARE_HTML, FNS), 'sim-bridge v2');
  const countRuns = (win: any) => { // eslint-disable-line @typescript-eslint/no-explicit-any
    win.runs = 0;
    win.runDemo = () => { win.runs += 1; };
  };

  it('ignores startScript from a window that is not the parent', () => {
    const h = runInSimDocument(inlineSource(), countRuns);
    h.fire({ type: 'startScript', script: 'demo' }, 'foreign');
    expect(h.win.runs, 'a foreign window started a script inside the sim').toBe(0);
  });

  it('still honours startScript from the real parent', () => {
    const h = runInSimDocument(inlineSource(), countRuns);
    h.fire({ type: 'startScript', script: 'demo' }, 'parent');
    expect(h.win.runs).toBe(1);
  });
});

// ── 4/5. Generated bridge.js — single-body and combined wrappers ──────────────

const RUN_BODY = 'window.runs = (window.runs || 0) + 1;\nreturn function () {};';

describe.each([
  ['wrapBridgeMainBody', () => wrapBridgeMainBody(RUN_BODY), { type: 'startScript' }],
  ['wrapBridgeCombined', () => wrapBridgeCombined(new Map([['sec1', RUN_BODY]])), { type: 'startScript', script: 'sec1' }],
])('%s — startScript', (_name, build, message) => {
  it('ignores startScript from a window that is not the parent', () => {
    const h = runInSimDocument(build(), (win) => { win.runs = 0; });
    h.fire(message, 'foreign');
    expect(h.win.runs, 'a foreign window started a section inside the sim').toBe(0);
  });

  it('still honours startScript from the real parent', () => {
    const h = runInSimDocument(build(), (win) => { win.runs = 0; });
    h.fire(message, 'parent');
    expect(h.win.runs).toBe(1);
  });
});

// ── 6. Published guidance overlay ─────────────────────────────────────────────

describe('guidance overlay — guidanceGate', () => {
  const entries: GuidanceEntryStored[] = [{
    id: 'cue1', kind: 'config', title: 'Cue', narration: 'Try it', enabled: true,
    trigger: { kind: 'config', predicateBody: 'return true;', observables: [], debounce: 1 },
    audioUrl: null, confidence: 1, warnings: [],
  }];
  /** The poll fires a cue only while the gate is open; three spaced ticks clear the throttle. */
  const pump = (h: Harness) => { h.flushRaf(1_000); h.flushRaf(2_000); h.flushRaf(3_000); };
  const cues = (h: Harness) => h.parentPosts.filter((m) => m.type === 'guidanceCue');

  // CONTROL. Without it, "no cue was posted" would pass for a harness that never fires cues at
  // all, and the two tests below would prove nothing in either direction.
  it('fires a cue when nobody closes the gate', () => {
    const h = runInSimDocument(wrapGuidanceCombined(entries));
    pump(h);
    expect(cues(h)).toHaveLength(1);
  });

  it('ignores guidanceGate from a window that is not the parent', () => {
    const h = runInSimDocument(wrapGuidanceCombined(entries));
    h.fire({ type: 'guidanceGate', active: false }, 'foreign');
    pump(h);
    expect(cues(h), 'a foreign window silenced every guidance cue').toHaveLength(1);
  });

  it('still honours guidanceGate from the real parent', () => {
    const h = runInSimDocument(wrapGuidanceCombined(entries));
    h.fire({ type: 'guidanceGate', active: false }, 'parent');
    pump(h);
    expect(cues(h)).toHaveLength(0);
  });
});
