packages:
  - 'backend-api'
  - 'client-web'
  - 'admin-web'
  - 'shared'
  - 'interactive-podcast-react'
allowBuilds:
  '@google/genai': true
  bson: true
  esbuild: true
  protobufjs: true
  sharp: true
