/**
 * D-14, the client half: what a REFUSED viewer sees.
 *
 * The avatar budget ships in `shadow`, so nothing here fires in production today. The day somebody
 * sets `AVATAR_BUDGET_MODE=enforce`, this screen is the first thing viewers meet — and before this
 * wiring every refusal arrived as an anonymous Error, showed the generic "couldn't start right now"
 * apology, and offered a `Try again` button guaranteed to be refused again the same second.
 *
 * The competing constraint is ui-ux-205: no server string reaches a viewer's screen. That rule is
 * kept by construction rather than by care — the copy rendered below is regenerated by the shared
 * module from a closed enum of three reasons, so the last test here is the one that matters most.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, act, cleanup, screen } from '@testing-library/react';

vi.mock('../lib/firebase', () => ({
  auth: { currentUser: { getIdToken: () => Promise.resolve('test-id-token') } },
}));

import { AvatarPopup } from '../components/avatar/AvatarPopup';

/** Answer /avatar/start with a refusal shaped exactly as the backend builds it. */
function refuseStart(status: number, body: unknown) {
  globalThis.fetch = vi.fn((url: RequestInfo | URL) => {
    if (!String(url).includes('/api/v1/avatar/start')) return Promise.resolve(new Response('{}'));
    return Promise.resolve(new Response(JSON.stringify(body), {
      status, headers: { 'Content-Type': 'application/json' },
    }));
  }) as unknown as typeof fetch;
}

const openPopup = async () => {
  render(<AvatarPopup open onClose={() => {}} projectId="p1" />);
  await act(async () => { await Promise.resolve(); await Promise.resolve(); });
};

describe('a refused viewer is told which kind of "not now" this is', () => {
  const realFetch = globalThis.fetch;
  let consoleError: ReturnType<typeof vi.spyOn>;

  beforeEach(() => {
    vi.useFakeTimers();
    consoleError = vi.spyOn(console, 'error').mockImplementation(() => {});
  });
  afterEach(() => {
    cleanup(); vi.useRealTimers(); globalThis.fetch = realFetch; consoleError.mockRestore();
  });

  it('says a platform-wide surge is not the viewer\'s fault', async () => {
    refuseStart(429, { message: 'x', reason: 'busy', retryAfterSec: 30 });
    await openPopup();

    expect(screen.getByText(/busy across the platform/i)).toBeTruthy();
    // And NOT the apology that says nothing.
    expect(screen.queryByText(/couldn't start right now/i)).toBeNull();
  });

  it('does not offer a retry the same limit will refuse again', async () => {
    refuseStart(429, { message: 'x', reason: 'limited', retryAfterSec: 30 });
    await openPopup();

    const retry = screen.getByRole('button', { name: /try again/i }) as HTMLButtonElement;
    expect(retry.disabled).toBe(true);
  });

  it('but gives the button back once the wait the SERVER named has passed', async () => {
    // The failure mode of the previous test taken alone: a viewer who waited exactly as asked
    // returns to a dead button and no way to reach the avatar short of reloading the page.
    refuseStart(429, { message: 'x', reason: 'limited', retryAfterSec: 30 });
    await openPopup();

    await act(async () => { vi.advanceTimersByTime(29_000); });
    expect((screen.getByRole('button', { name: /try again/i }) as HTMLButtonElement).disabled).toBe(true);

    await act(async () => { vi.advanceTimersByTime(2_000); });
    expect((screen.getByRole('button', { name: /try again/i }) as HTMLButtonElement).disabled).toBe(false);
  });

  it('keeps the generic apology for a failure that is NOT an explained refusal', async () => {
    // A crash is not a refusal, and the product must not start claiming a limit it never hit.
    refuseStart(500, { message: 'Internal Server Error' });
    await openPopup();

    expect(screen.getByText(/couldn't start right now/i)).toBeTruthy();
    expect((screen.getByRole('button', { name: /try again/i }) as HTMLButtonElement).disabled).toBe(false);
  });

  it('NEVER renders the server\'s own string, even beside a valid reason', async () => {
    // ui-ux-205, kept by construction. A body carrying a real `reason` must not become a licence
    // to print whatever text arrived with it — that is how a connection string or a stack trace
    // reaches a viewer's screen.
    refuseStart(429, {
      reason: 'busy',
      retryAfterSec: 30,
      message: 'FATAL: password authentication failed for user "flowvid" at 10.0.0.4:5432',
    });
    await openPopup();

    for (const secret of ['password', 'FATAL', 'flowvid', '10.0.0.4']) {
      expect(document.body.textContent, secret).not.toContain(secret);
    }
    expect(screen.getByText(/busy across the platform/i)).toBeTruthy();
  });
});
