/**
 * PRODUCTION-PARITY proof for the delayed-ack fixture — executed against the GENERATED BYTES.
 *
 * The fixture exists to produce the one input class the runtime's matchesPending guards: a stale
 * SCRIPT_APPLIED surviving a supersede or a teardown, exactly as production's `_sysRaf(_ack)` —
 * scheduled outside `_trackTimers` — survives both. An earlier version was POLITER than
 * production (it cancelled pending acks on supersede/stop), which silently removed the entire
 * class from e2e coverage. These tests run the real emitted bridge in a VM so that regression
 * cannot come back unnoticed.
 */
import { describe, it, expect } from 'vitest';
import vm from 'node:vm';
import {
  delayedAckBridge,
  DELAYED_ACK_POLICY,
  FIXTURE_SECTIONS,
  FIXTURE_DELAYED_SECTIONS,
  BAD_TOKEN_DELTA,
} from '../gen-sim-fixture.js';

const A = FIXTURE_SECTIONS.A;
const B = FIXTURE_SECTIONS.B;
const LATE = FIXTURE_DELAYED_SECTIONS.LATE;
const BAD = FIXTURE_DELAYED_SECTIONS.BADTOKEN;

interface Posted { type: string; script?: string; token?: number }

/** Run the emitted bridge source and drive it with a message sequence. */
async function drive(steps: object[], settleMs = 700): Promise<Posted[]> {
  const posted: Posted[] = [];
  const listeners: ((e: { data: unknown }) => void)[] = [];
  const el = { style: {}, setAttribute() {}, remove() {} };
  const ctx: Record<string, unknown> = {
    console, Date, Object, JSON, String, Math, setTimeout, clearTimeout,
    document: { getElementById: () => el, querySelector: () => null },
    parent: { postMessage: (m: Posted) => posted.push(m) },
    location: { search: '', hash: '' },
    addEventListener: (t: string, f: (e: { data: unknown }) => void) => { if (t === 'message') listeners.push(f); },
  };
  ctx.window = ctx;
  vm.createContext(ctx);
  const entries = new Map<string, string>([
    [A, "return function(){};"], [B, "return function(){};"],
    [LATE, "return function(){};"], [BAD, "return function(){};"],
  ]);
  // The SAME policy main() emits with — an unpolicied bridge is a different fixture entirely.
  vm.runInContext(delayedAckBridge(entries, DELAYED_ACK_POLICY), ctx as vm.Context);
  // `source: ctx.parent` — the bridge ignores messages from any other window (simulation-004).
  for (const st of steps) listeners.forEach((f) => f({ data: st, source: ctx.parent }));
  await new Promise((r) => setTimeout(r, settleMs));
  return posted.filter((m) => m.type === 'SCRIPT_APPLIED');
}

describe('delayed-ack fixture — production parity, proven on the emitted bytes', () => {
  it('a SUPERSEDED activation still acknowledges, with its ORIGINAL token', async () => {
    const acks = await drive([
      { type: 'startScript', script: LATE, params: {}, token: 1 },
      { type: 'startScript', script: B, params: {}, token: 2 },
    ]);
    expect(acks.map((a) => [a.script, a.token])).toEqual(
      expect.arrayContaining([[LATE, 1], [B, 2]]),
    );
    // …and the stale one carries the SUPERSEDED token, never the live one.
    expect(acks.find((a) => a.script === LATE)!.token).toBe(1);
  });

  it('stopScript does NOT cancel the pending acknowledgement', async () => {
    const acks = await drive([
      { type: 'startScript', script: LATE, params: {}, token: 3 },
      { type: 'stopScript' },
    ]);
    expect(acks.map((a) => [a.script, a.token]), 'the teardown cancelled the ack — politer than production')
      .toEqual([[LATE, 3]]);
  });

  it('with NO lifecycle event, a retained acknowledgement is NOT released', async () => {
    const acks = await drive([{ type: 'startScript', script: LATE, params: {}, token: 4 }]);
    expect(acks, 'the retained ack fired without any lifecycle event').toEqual([]);
  });

  it('the newly received activation is never released as part of the retained snapshot', async () => {
    // The audited self-release bug: releasing whatever is retained AFTER applying the new section
    // also fired the ack the new activation itself had just retained — so LATE acknowledged its
    // own arrival and was never stale. LATE→LATE: the second must stay retained.
    const acks = await drive([
      { type: 'startScript', script: LATE, params: {}, token: 5 },
      { type: 'startScript', script: LATE, params: {}, token: 6 },
    ]);
    expect(acks.map((a) => a.token), 'the new activation released its own ack').toEqual([5]);
  });

  it('BADTOKEN acknowledges with a token that can never match the activation', async () => {
    const acks = await drive([{ type: 'startScript', script: BAD, params: {}, token: 10 }]);
    expect(acks.map((a) => [a.script, a.token])).toEqual([[BAD, 10 + BAD_TOKEN_DELTA]]);
  });

  it('an ordinary section still acknowledges promptly and validly (the control)', async () => {
    const acks = await drive([{ type: 'startScript', script: A, params: {}, token: 20 }]);
    expect(acks.map((a) => [a.script, a.token])).toEqual([[A, 20]]);
  });
});
